Menambah terjemahan embed bahasa Melayu
noaione/naoTimesUI pull request #236
Opened 2024-07-25 08:51 UTC by niskala5570

2024-07-25 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/noaione/naoTimesUI?pullRequest=236) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/noaione/naoTimesUI?pullRequest=236) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/noaione/naoTimesUI?pullRequest=236) it.</sub>

2024-07-25 14:16 UTC, noaione requested changes
Di file `i18n/index.ts`, tolong import dua file ini setelah bagian ini:
https://github.com/noaione/naoTimesUI/blob/master/i18n/index.ts#L4-L8

Habis itu tambah locale ke sini: https://github.com/noaione/naoTimesUI/blob/master/i18n/index.ts#L16

Dan untuk waktu/time ago tambah di sini: https://github.com/noaione/naoTimesUI/blob/master/i18n/index.ts#L26

2024-07-26 03:55 UTC, noaione requested changes

2024-07-26 03:55 UTC, noaione commented on i18n/index.ts
> +import { Locale as LocaleJP, TimeAgoLocale as TimeAgoLocaleJP } from "./ms";
```ts
import { Locale as LocaleMS, TimeAgoLocale as TimeAgoLocaleMS } from "./ms";
```

2024-07-26 03:55 UTC, noaione commented on i18n/index.ts
> +import { Locale as LocaleJP, TimeAgoLocale as TimeAgoLocaleJP } from "./ms_Arab";
```ts
import { Locale as LocaleMSArab, TimeAgoLocale as TimeAgoLocaleMSArab } from "./ms_Arab";
```

2024-07-26 08:02 UTC, niskala5570 commented
Maaf tak perasan, harapnya dah boleh

2024-07-26 08:48 UTC, merged

2024-07-26 08:49 UTC, noaione commented
Thanks!